name: miscelanea
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^10.1.2
  google_fonts: ^6.0.0
  local_auth: ^2.1.7
  provider: ^6.0.5
  flutter_riverpod: ^2.4.0
  splash_view: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/iconos/icono.png"
  adaptive_icon_background: "assets/iconos/icono.png"

flutter:
  uses-material-design: true
